### ISSUE TITLE
请问楼主，大部分组件在引用后，编译为小程序代码后不显示是为什么呢

### ISSUE THREAD

**Issue by chenp1204** [wzs28150/cool-kbone-vant#2]
大部分组件在引用后，编译为小程序代码后不显示是为什么呢，是否因为没在生成后的小程序代码里声明引用吗，而且并没有看到报错~

**Comment by chenp1204** [comment]
![微信图片_20200518224139](https://user-images.githubusercontent.com/29192482/82226270-df416c80-9958-11ea-859c-d70e466e7377.png)

**Comment by wzs28150** [comment]
main.mp.js 文件中没有引入vant吧
